spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/chat
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size : 100


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

security:
  jwt:
    token:
      secret-key: secret
      expire-length: 3600000

